platform :ios, '8.0'
use_frameworks!

target 'TotalDemo' do

  pod 'Masonry'
  pod 'AFNetworking'
  pod 'MJRefresh'
  
  #Lottie动画控件
  pod 'lottie-ios'

  #YYKit
  pod 'YYKit'
  
  #图片加载
  pod 'SDWebImage'
  
  #Firebase 远程配置
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'


end

